beaker test file fixes for puppet6/dual-mode
puppetlabs/cisco-network-puppet-module pull request #103
Opened 2019-01-11 21:58 UTC by chrisvanheuveln

I made a few changes / slight re-factoring of utilitylib.rb while testing `puppet6` branch on one of our F3-enabled n7k's. I only focused on the failed tests that you reported and got all of them working now. 
We still have to run the full suite of tests next week.  Thanks, Chris

2019-01-14 15:53 UTC, Thomas-Franklin requested changes
There seems to be a mixture of keyword arguments and positional arguments, i.e.

```
def test_set(agent, cmd, ignore_errors=false)
```

But then when calling test_set from some of the methods keyword arguments are used, i.e.

```
  test_set(agent, 'no ip domain-name test.xyz', ignore_errors: true)
```

Which means that ignore_errors will remain as `false` as this is the default in the positional argument.

Other than that then it should be fine to merge these changes as it is a nice refactor.

2019-01-14 19:07 UTC, chrisvanheuveln commented
Thanks for the review. That suspect code actually works but it was a workaround for an ArgumentError problem we hit when passing keyword arguments through several worker methods. I figured out the proper way to do this though so I'll remove the workaround in my next commit.

fyi, here's a simple version of the original problem:

```
BAD
def com(ig: false); puts ig; end
ig=true
com(ig)
ArgumentError: wrong number of arguments (given 1, expected 0)

GOOD
def com(ig: false); puts ig; end
com(ig: ig)
=> true
```

2019-01-14 20:13 UTC, chrisvanheuveln commented
@Thomas-Franklin That last commit should be the last of my changes for this PR. Please review when you have a chance. 
Thanks, Chris

2019-01-14 20:51 UTC, chrisvanheuveln commented on tests/beaker_tests/cisco_interface/test_interface_svi.rb
> +  remove_interface(agent, intf)
Note: `remove_interface` now ignores errors so this call should be fine.

2019-01-15 09:14 UTC, Thomas-Franklin commented
> @Thomas-Franklin That last commit should be the last of my changes for this PR. I'm getting 100% pass rate now for the set of n7k tests that were failing before my PR.
> Please review when you have a chance.
> Thanks, Chris

I will have a look over it now and it should hopefully be merged by time you're online @chrisvanheuveln. Thanks for taking the time and resolving these issues.

2019-01-15 13:22 UTC, Thomas-Franklin approved these changes

2019-01-15 13:24 UTC, merged