(maint) Allow beaker host to be set using ip, hostname or vmhostname
puppetlabs/cisco-network-puppet-module pull request #94
Opened 2018-12-13 16:28 UTC by willmeek

2018-12-13 16:33 UTC, shermdog commented
:+1:  :)

2018-12-13 16:44 UTC, Thomas-Franklin requested changes
There are a few other places that will need changed: `create_agentless_device_conf` `command_config`, `test_set` etc.

2018-12-13 16:59 UTC, willmeek commented
Changing this to be a utility function

2018-12-14 15:47 UTC, Thomas-Franklin approved these changes

2018-12-14 15:48 UTC, merged